// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lobbyResponse.proto

package com.fagp.basics.core.protobuf.lobby.response;

public final class LobbyProtoResponse {
  private LobbyProtoResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lobby.LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *user ID
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <pre>
     *user ID
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     * dianh
     * </pre>
     *
     * <code>string phone = 2;</code>
     */
    java.lang.String getPhone();
    /**
     * <pre>
     * dianh
     * </pre>
     *
     * <code>string phone = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <pre>
     *user 钱包
     * </pre>
     *
     * <code>int32 money = 3;</code>
     */
    int getMoney();

    /**
     * <pre>
     * 金币
     * </pre>
     *
     * <code>int32 gcode = 4;</code>
     */
    int getGcode();
  }
  /**
   * <pre>
   *登录Response
   * </pre>
   *
   * Protobuf type {@code com.lobby.LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lobby.LoginResponse)
      LoginResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
      uid_ = "";
      phone_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 24: {

              money_ = input.readInt32();
              break;
            }
            case 32: {

              gcode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_LoginResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.class, com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     *user ID
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *user ID
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 2;
    private volatile java.lang.Object phone_;
    /**
     * <pre>
     * dianh
     * </pre>
     *
     * <code>string phone = 2;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * dianh
     * </pre>
     *
     * <code>string phone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONEY_FIELD_NUMBER = 3;
    private int money_;
    /**
     * <pre>
     *user 钱包
     * </pre>
     *
     * <code>int32 money = 3;</code>
     */
    public int getMoney() {
      return money_;
    }

    public static final int GCODE_FIELD_NUMBER = 4;
    private int gcode_;
    /**
     * <pre>
     * 金币
     * </pre>
     *
     * <code>int32 gcode = 4;</code>
     */
    public int getGcode() {
      return gcode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phone_);
      }
      if (money_ != 0) {
        output.writeInt32(3, money_);
      }
      if (gcode_ != 0) {
        output.writeInt32(4, gcode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phone_);
      }
      if (money_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, money_);
      }
      if (gcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse)) {
        return super.equals(obj);
      }
      com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse other = (com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (getMoney()
          != other.getMoney()) return false;
      if (getGcode()
          != other.getGcode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + getMoney();
      hash = (37 * hash) + GCODE_FIELD_NUMBER;
      hash = (53 * hash) + getGcode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *登录Response
     * </pre>
     *
     * Protobuf type {@code com.lobby.LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lobby.LoginResponse)
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_LoginResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.class, com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        phone_ = "";

        money_ = 0;

        gcode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_LoginResponse_descriptor;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse getDefaultInstanceForType() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse build() {
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse buildPartial() {
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse result = new com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse(this);
        result.uid_ = uid_;
        result.phone_ = phone_;
        result.money_ = money_;
        result.gcode_ = gcode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse) {
          return mergeFrom((com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse other) {
        if (other == com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (other.getMoney() != 0) {
          setMoney(other.getMoney());
        }
        if (other.getGcode() != 0) {
          setGcode(other.getGcode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       *user ID
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *user ID
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *user ID
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *user ID
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *user ID
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <pre>
       * dianh
       * </pre>
       *
       * <code>string phone = 2;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * dianh
       * </pre>
       *
       * <code>string phone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * dianh
       * </pre>
       *
       * <code>string phone = 2;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * dianh
       * </pre>
       *
       * <code>string phone = 2;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * dianh
       * </pre>
       *
       * <code>string phone = 2;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private int money_ ;
      /**
       * <pre>
       *user 钱包
       * </pre>
       *
       * <code>int32 money = 3;</code>
       */
      public int getMoney() {
        return money_;
      }
      /**
       * <pre>
       *user 钱包
       * </pre>
       *
       * <code>int32 money = 3;</code>
       */
      public Builder setMoney(int value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *user 钱包
       * </pre>
       *
       * <code>int32 money = 3;</code>
       */
      public Builder clearMoney() {
        
        money_ = 0;
        onChanged();
        return this;
      }

      private int gcode_ ;
      /**
       * <pre>
       * 金币
       * </pre>
       *
       * <code>int32 gcode = 4;</code>
       */
      public int getGcode() {
        return gcode_;
      }
      /**
       * <pre>
       * 金币
       * </pre>
       *
       * <code>int32 gcode = 4;</code>
       */
      public Builder setGcode(int value) {
        
        gcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 金币
       * </pre>
       *
       * <code>int32 gcode = 4;</code>
       */
      public Builder clearGcode() {
        
        gcode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lobby.LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:com.lobby.LoginResponse)
    private static final com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse();
    }

    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      @java.lang.Override
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EFTResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lobby.EFTResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 转账金额
     * </pre>
     *
     * <code>int32 goldNum = 3;</code>
     */
    int getGoldNum();

    /**
     * <pre>
     *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
     * </pre>
     *
     * <code>int32 tow = 4;</code>
     */
    int getTow();
  }
  /**
   * <pre>
   *转账 Response
   * </pre>
   *
   * Protobuf type {@code com.lobby.EFTResponse}
   */
  public  static final class EFTResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lobby.EFTResponse)
      EFTResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EFTResponse.newBuilder() to construct.
    private EFTResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EFTResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EFTResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EFTResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 24: {

              goldNum_ = input.readInt32();
              break;
            }
            case 32: {

              tow_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_EFTResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_EFTResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.class, com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.Builder.class);
    }

    public static final int GOLDNUM_FIELD_NUMBER = 3;
    private int goldNum_;
    /**
     * <pre>
     * 转账金额
     * </pre>
     *
     * <code>int32 goldNum = 3;</code>
     */
    public int getGoldNum() {
      return goldNum_;
    }

    public static final int TOW_FIELD_NUMBER = 4;
    private int tow_;
    /**
     * <pre>
     *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
     * </pre>
     *
     * <code>int32 tow = 4;</code>
     */
    public int getTow() {
      return tow_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (goldNum_ != 0) {
        output.writeInt32(3, goldNum_);
      }
      if (tow_ != 0) {
        output.writeInt32(4, tow_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (goldNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, goldNum_);
      }
      if (tow_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tow_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse)) {
        return super.equals(obj);
      }
      com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse other = (com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse) obj;

      if (getGoldNum()
          != other.getGoldNum()) return false;
      if (getTow()
          != other.getTow()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GOLDNUM_FIELD_NUMBER;
      hash = (53 * hash) + getGoldNum();
      hash = (37 * hash) + TOW_FIELD_NUMBER;
      hash = (53 * hash) + getTow();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *转账 Response
     * </pre>
     *
     * Protobuf type {@code com.lobby.EFTResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lobby.EFTResponse)
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_EFTResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_EFTResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.class, com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        goldNum_ = 0;

        tow_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.internal_static_com_lobby_EFTResponse_descriptor;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse getDefaultInstanceForType() {
        return com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse build() {
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse buildPartial() {
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse result = new com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse(this);
        result.goldNum_ = goldNum_;
        result.tow_ = tow_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse) {
          return mergeFrom((com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse other) {
        if (other == com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.getDefaultInstance()) return this;
        if (other.getGoldNum() != 0) {
          setGoldNum(other.getGoldNum());
        }
        if (other.getTow() != 0) {
          setTow(other.getTow());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int goldNum_ ;
      /**
       * <pre>
       * 转账金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public int getGoldNum() {
        return goldNum_;
      }
      /**
       * <pre>
       * 转账金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public Builder setGoldNum(int value) {
        
        goldNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 转账金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public Builder clearGoldNum() {
        
        goldNum_ = 0;
        onChanged();
        return this;
      }

      private int tow_ ;
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public int getTow() {
        return tow_;
      }
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public Builder setTow(int value) {
        
        tow_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public Builder clearTow() {
        
        tow_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lobby.EFTResponse)
    }

    // @@protoc_insertion_point(class_scope:com.lobby.EFTResponse)
    private static final com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse();
    }

    public static com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EFTResponse>
        PARSER = new com.google.protobuf.AbstractParser<EFTResponse>() {
      @java.lang.Override
      public EFTResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EFTResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EFTResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EFTResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_LoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_LoginResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_EFTResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_EFTResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023lobbyResponse.proto\022\tcom.lobby\"I\n\rLogi" +
      "nResponse\022\013\n\003uid\030\001 \001(\t\022\r\n\005phone\030\002 \001(\t\022\r\n" +
      "\005money\030\003 \001(\005\022\r\n\005gcode\030\004 \001(\005\"+\n\013EFTRespon" +
      "se\022\017\n\007goldNum\030\003 \001(\005\022\013\n\003tow\030\004 \001(\005BV\n,com." +
      "fagp.basics.core.protobuf.lobby.response" +
      "B\022LobbyProtoResponse\252\002\021sk.WellKnownTypes" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_lobby_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lobby_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_LoginResponse_descriptor,
        new java.lang.String[] { "Uid", "Phone", "Money", "Gcode", });
    internal_static_com_lobby_EFTResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lobby_EFTResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_EFTResponse_descriptor,
        new java.lang.String[] { "GoldNum", "Tow", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
