// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lobbyRequest.proto

package com.fagp.basics.core.protobuf.lobby.request;

public final class LobbyProtoRequest {
  private LobbyProtoRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lobby.LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getHeader();
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>string phone = 2;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string mac = 4;</code>
     */
    java.lang.String getMac();
    /**
     * <code>string mac = 4;</code>
     */
    com.google.protobuf.ByteString
        getMacBytes();
  }
  /**
   * <pre>
   *登录 Request header
   * </pre>
   *
   * Protobuf type {@code com.lobby.LoginRequest}
   */
  public  static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lobby.LoginRequest)
      LoginRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      phone_ = "";
      password_ = "";
      mac_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              mac_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_LoginRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest.class, com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader header_;
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getHeader() {
      return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int PHONE_FIELD_NUMBER = 2;
    private volatile java.lang.Object phone_;
    /**
     * <code>string phone = 2;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAC_FIELD_NUMBER = 4;
    private volatile java.lang.Object mac_;
    /**
     * <code>string mac = 4;</code>
     */
    public java.lang.String getMac() {
      java.lang.Object ref = mac_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      }
    }
    /**
     * <code>string mac = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phone_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      if (!getMacBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mac_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phone_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      if (!getMacBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mac_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest)) {
        return super.equals(obj);
      }
      com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest other = (com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getMac()
          .equals(other.getMac())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *登录 Request header
     * </pre>
     *
     * Protobuf type {@code com.lobby.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lobby.LoginRequest)
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_LoginRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest.class, com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest.Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        phone_ = "";

        password_ = "";

        mac_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_LoginRequest_descriptor;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest getDefaultInstanceForType() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest build() {
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest buildPartial() {
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest result = new com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.phone_ = phone_;
        result.password_ = password_;
        result.mac_ = mac_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest) {
          return mergeFrom((com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest other) {
        if (other == com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getMac().isEmpty()) {
          mac_ = other.mac_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder setHeader(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder setHeader(
          com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder mergeHeader(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 2;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 2;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 2;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 2;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mac_ = "";
      /**
       * <code>string mac = 4;</code>
       */
      public java.lang.String getMac() {
        java.lang.Object ref = mac_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mac_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mac = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMacBytes() {
        java.lang.Object ref = mac_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mac_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mac = 4;</code>
       */
      public Builder setMac(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 4;</code>
       */
      public Builder clearMac() {
        
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      /**
       * <code>string mac = 4;</code>
       */
      public Builder setMacBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mac_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lobby.LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:com.lobby.LoginRequest)
    private static final com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest();
    }

    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      @java.lang.Override
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EFTRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lobby.EFTRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getHeader();
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>string uid = 2;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>int32 goldNum = 3;</code>
     */
    int getGoldNum();

    /**
     * <pre>
     *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
     * </pre>
     *
     * <code>int32 tow = 4;</code>
     */
    int getTow();
  }
  /**
   * <pre>
   *转账 Request
   * </pre>
   *
   * Protobuf type {@code com.lobby.EFTRequest}
   */
  public  static final class EFTRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lobby.EFTRequest)
      EFTRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EFTRequest.newBuilder() to construct.
    private EFTRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EFTRequest() {
      uid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EFTRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EFTRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 24: {

              goldNum_ = input.readInt32();
              break;
            }
            case 32: {

              tow_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_EFTRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_EFTRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest.class, com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader header_;
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getHeader() {
      return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.fagp.GameRequestHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int UID_FIELD_NUMBER = 2;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 2;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOLDNUM_FIELD_NUMBER = 3;
    private int goldNum_;
    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>int32 goldNum = 3;</code>
     */
    public int getGoldNum() {
      return goldNum_;
    }

    public static final int TOW_FIELD_NUMBER = 4;
    private int tow_;
    /**
     * <pre>
     *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
     * </pre>
     *
     * <code>int32 tow = 4;</code>
     */
    public int getTow() {
      return tow_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uid_);
      }
      if (goldNum_ != 0) {
        output.writeInt32(3, goldNum_);
      }
      if (tow_ != 0) {
        output.writeInt32(4, tow_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uid_);
      }
      if (goldNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, goldNum_);
      }
      if (tow_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tow_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest)) {
        return super.equals(obj);
      }
      com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest other = (com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getUid()
          .equals(other.getUid())) return false;
      if (getGoldNum()
          != other.getGoldNum()) return false;
      if (getTow()
          != other.getTow()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + GOLDNUM_FIELD_NUMBER;
      hash = (53 * hash) + getGoldNum();
      hash = (37 * hash) + TOW_FIELD_NUMBER;
      hash = (53 * hash) + getTow();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *转账 Request
     * </pre>
     *
     * Protobuf type {@code com.lobby.EFTRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lobby.EFTRequest)
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_EFTRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_EFTRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest.class, com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest.Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        uid_ = "";

        goldNum_ = 0;

        tow_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.internal_static_com_lobby_EFTRequest_descriptor;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest getDefaultInstanceForType() {
        return com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest build() {
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest buildPartial() {
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest result = new com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.uid_ = uid_;
        result.goldNum_ = goldNum_;
        result.tow_ = tow_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest) {
          return mergeFrom((com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest other) {
        if (other == com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (other.getGoldNum() != 0) {
          setGoldNum(other.getGoldNum());
        }
        if (other.getTow() != 0) {
          setTow(other.getTow());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder setHeader(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder setHeader(
          com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder mergeHeader(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.fagp.GameRequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 2;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private int goldNum_ ;
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public int getGoldNum() {
        return goldNum_;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public Builder setGoldNum(int value) {
        
        goldNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public Builder clearGoldNum() {
        
        goldNum_ = 0;
        onChanged();
        return this;
      }

      private int tow_ ;
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public int getTow() {
        return tow_;
      }
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public Builder setTow(int value) {
        
        tow_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public Builder clearTow() {
        
        tow_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lobby.EFTRequest)
    }

    // @@protoc_insertion_point(class_scope:com.lobby.EFTRequest)
    private static final com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest();
    }

    public static com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EFTRequest>
        PARSER = new com.google.protobuf.AbstractParser<EFTRequest>() {
      @java.lang.Override
      public EFTRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EFTRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EFTRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EFTRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fagp.basics.core.protobuf.lobby.request.LobbyProtoRequest.EFTRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_LoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_EFTRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_EFTRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022lobbyRequest.proto\022\tcom.lobby\032\014header." +
      "proto\"i\n\014LoginRequest\022+\n\006header\030\001 \001(\0132\033." +
      "com.fagp.GameRequestHeader\022\r\n\005phone\030\002 \001(" +
      "\t\022\020\n\010password\030\003 \001(\t\022\013\n\003mac\030\004 \001(\t\"d\n\nEFTR" +
      "equest\022+\n\006header\030\001 \001(\0132\033.com.fagp.GameRe" +
      "questHeader\022\013\n\003uid\030\002 \001(\t\022\017\n\007goldNum\030\003 \001(" +
      "\005\022\013\n\003tow\030\004 \001(\005B@\n+com.fagp.basics.core.p" +
      "rotobuf.lobby.requestB\021LobbyProtoRequest" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fagp.basics.core.protobuf.aheader.Header.getDescriptor(),
        });
    internal_static_com_lobby_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lobby_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_LoginRequest_descriptor,
        new java.lang.String[] { "Header", "Phone", "Password", "Mac", });
    internal_static_com_lobby_EFTRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lobby_EFTRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_EFTRequest_descriptor,
        new java.lang.String[] { "Header", "Uid", "GoldNum", "Tow", });
    com.fagp.basics.core.protobuf.aheader.Header.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
