// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.fagp.basics.core.protobuf.aheader;

public final class Header {
  private Header() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameResponseHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fagp.GameResponseHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *命令号
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    int getCmd();

    /**
     * <pre>
     *250 表示成功，其他数值表示有错误
     * </pre>
     *
     * <code>int32 status_code = 3;</code>
     */
    int getStatusCode();

    /**
     * <pre>
     * 状态值 成功则是 success 错误则反回错误对应说明
     * </pre>
     *
     * <code>string status_msg = 4;</code>
     */
    java.lang.String getStatusMsg();
    /**
     * <pre>
     * 状态值 成功则是 success 错误则反回错误对应说明
     * </pre>
     *
     * <code>string status_msg = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusMsgBytes();

    /**
     * <pre>
     * 这个是版本号 目前没有用 主要是应对接口变动兼容老版本
     * </pre>
     *
     * <code>int32 version = 5;</code>
     */
    int getVersion();
  }
  /**
   * <pre>
   *服务器 返回前端的 header
   * </pre>
   *
   * Protobuf type {@code com.fagp.GameResponseHeader}
   */
  public  static final class GameResponseHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fagp.GameResponseHeader)
      GameResponseHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameResponseHeader.newBuilder() to construct.
    private GameResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameResponseHeader() {
      statusMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameResponseHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameResponseHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              cmd_ = input.readInt32();
              break;
            }
            case 24: {

              statusCode_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              statusMsg_ = s;
              break;
            }
            case 40: {

              version_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameResponseHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.class, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <pre>
     *命令号
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int STATUS_CODE_FIELD_NUMBER = 3;
    private int statusCode_;
    /**
     * <pre>
     *250 表示成功，其他数值表示有错误
     * </pre>
     *
     * <code>int32 status_code = 3;</code>
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int STATUS_MSG_FIELD_NUMBER = 4;
    private volatile java.lang.Object statusMsg_;
    /**
     * <pre>
     * 状态值 成功则是 success 错误则反回错误对应说明
     * </pre>
     *
     * <code>string status_msg = 4;</code>
     */
    public java.lang.String getStatusMsg() {
      java.lang.Object ref = statusMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 状态值 成功则是 success 错误则反回错误对应说明
     * </pre>
     *
     * <code>string status_msg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusMsgBytes() {
      java.lang.Object ref = statusMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private int version_;
    /**
     * <pre>
     * 这个是版本号 目前没有用 主要是应对接口变动兼容老版本
     * </pre>
     *
     * <code>int32 version = 5;</code>
     */
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(2, cmd_);
      }
      if (statusCode_ != 0) {
        output.writeInt32(3, statusCode_);
      }
      if (!getStatusMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, statusMsg_);
      }
      if (version_ != 0) {
        output.writeInt32(5, version_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmd_);
      }
      if (statusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, statusCode_);
      }
      if (!getStatusMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, statusMsg_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader)) {
        return super.equals(obj);
      }
      com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader other = (com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader) obj;

      if (getCmd()
          != other.getCmd()) return false;
      if (getStatusCode()
          != other.getStatusCode()) return false;
      if (!getStatusMsg()
          .equals(other.getStatusMsg())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + STATUS_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode();
      hash = (37 * hash) + STATUS_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getStatusMsg().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *服务器 返回前端的 header
     * </pre>
     *
     * Protobuf type {@code com.fagp.GameResponseHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fagp.GameResponseHeader)
        com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameResponseHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.class, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        statusCode_ = 0;

        statusMsg_ = "";

        version_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameResponseHeader_descriptor;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getDefaultInstanceForType() {
        return com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader build() {
        com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader buildPartial() {
        com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader result = new com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader(this);
        result.cmd_ = cmd_;
        result.statusCode_ = statusCode_;
        result.statusMsg_ = statusMsg_;
        result.version_ = version_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader) {
          return mergeFrom((com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader other) {
        if (other == com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getStatusCode() != 0) {
          setStatusCode(other.getStatusCode());
        }
        if (!other.getStatusMsg().isEmpty()) {
          statusMsg_ = other.statusMsg_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ ;
      /**
       * <pre>
       *命令号
       * </pre>
       *
       * <code>int32 cmd = 2;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *命令号
       * </pre>
       *
       * <code>int32 cmd = 2;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令号
       * </pre>
       *
       * <code>int32 cmd = 2;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <pre>
       *250 表示成功，其他数值表示有错误
       * </pre>
       *
       * <code>int32 status_code = 3;</code>
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <pre>
       *250 表示成功，其他数值表示有错误
       * </pre>
       *
       * <code>int32 status_code = 3;</code>
       */
      public Builder setStatusCode(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *250 表示成功，其他数值表示有错误
       * </pre>
       *
       * <code>int32 status_code = 3;</code>
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object statusMsg_ = "";
      /**
       * <pre>
       * 状态值 成功则是 success 错误则反回错误对应说明
       * </pre>
       *
       * <code>string status_msg = 4;</code>
       */
      public java.lang.String getStatusMsg() {
        java.lang.Object ref = statusMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statusMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 状态值 成功则是 success 错误则反回错误对应说明
       * </pre>
       *
       * <code>string status_msg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusMsgBytes() {
        java.lang.Object ref = statusMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 状态值 成功则是 success 错误则反回错误对应说明
       * </pre>
       *
       * <code>string status_msg = 4;</code>
       */
      public Builder setStatusMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态值 成功则是 success 错误则反回错误对应说明
       * </pre>
       *
       * <code>string status_msg = 4;</code>
       */
      public Builder clearStatusMsg() {
        
        statusMsg_ = getDefaultInstance().getStatusMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态值 成功则是 success 错误则反回错误对应说明
       * </pre>
       *
       * <code>string status_msg = 4;</code>
       */
      public Builder setStatusMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusMsg_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * 这个是版本号 目前没有用 主要是应对接口变动兼容老版本
       * </pre>
       *
       * <code>int32 version = 5;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 这个是版本号 目前没有用 主要是应对接口变动兼容老版本
       * </pre>
       *
       * <code>int32 version = 5;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 这个是版本号 目前没有用 主要是应对接口变动兼容老版本
       * </pre>
       *
       * <code>int32 version = 5;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.fagp.GameResponseHeader)
    }

    // @@protoc_insertion_point(class_scope:com.fagp.GameResponseHeader)
    private static final com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader();
    }

    public static com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameResponseHeader>
        PARSER = new com.google.protobuf.AbstractParser<GameResponseHeader>() {
      @java.lang.Override
      public GameResponseHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameResponseHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameResponseHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameResponseHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameRequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fagp.GameRequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *命令号
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    int getCmd();

    /**
     * <pre>
     *版本号 目前没有用  主要是应对接口变动兼容老版本
     * </pre>
     *
     * <code>int32 version = 3;</code>
     */
    int getVersion();
  }
  /**
   * <pre>
   *请求服务器
   * </pre>
   *
   * Protobuf type {@code com.fagp.GameRequestHeader}
   */
  public  static final class GameRequestHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fagp.GameRequestHeader)
      GameRequestHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameRequestHeader.newBuilder() to construct.
    private GameRequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameRequestHeader() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameRequestHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameRequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              cmd_ = input.readInt32();
              break;
            }
            case 24: {

              version_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameRequestHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameRequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.class, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <pre>
     *命令号
     * </pre>
     *
     * <code>int32 cmd = 2;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private int version_;
    /**
     * <pre>
     *版本号 目前没有用  主要是应对接口变动兼容老版本
     * </pre>
     *
     * <code>int32 version = 3;</code>
     */
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(2, cmd_);
      }
      if (version_ != 0) {
        output.writeInt32(3, version_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmd_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader)) {
        return super.equals(obj);
      }
      com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader other = (com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader) obj;

      if (getCmd()
          != other.getCmd()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求服务器
     * </pre>
     *
     * Protobuf type {@code com.fagp.GameRequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fagp.GameRequestHeader)
        com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameRequestHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameRequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.class, com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        version_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fagp.basics.core.protobuf.aheader.Header.internal_static_com_fagp_GameRequestHeader_descriptor;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getDefaultInstanceForType() {
        return com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader build() {
        com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader buildPartial() {
        com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader result = new com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader(this);
        result.cmd_ = cmd_;
        result.version_ = version_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader) {
          return mergeFrom((com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader other) {
        if (other == com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ ;
      /**
       * <pre>
       *命令号
       * </pre>
       *
       * <code>int32 cmd = 2;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *命令号
       * </pre>
       *
       * <code>int32 cmd = 2;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令号
       * </pre>
       *
       * <code>int32 cmd = 2;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       *版本号 目前没有用  主要是应对接口变动兼容老版本
       * </pre>
       *
       * <code>int32 version = 3;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *版本号 目前没有用  主要是应对接口变动兼容老版本
       * </pre>
       *
       * <code>int32 version = 3;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *版本号 目前没有用  主要是应对接口变动兼容老版本
       * </pre>
       *
       * <code>int32 version = 3;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.fagp.GameRequestHeader)
    }

    // @@protoc_insertion_point(class_scope:com.fagp.GameRequestHeader)
    private static final com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader();
    }

    public static com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameRequestHeader>
        PARSER = new com.google.protobuf.AbstractParser<GameRequestHeader>() {
      @java.lang.Override
      public GameRequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameRequestHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameRequestHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameRequestHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fagp.basics.core.protobuf.aheader.Header.GameRequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fagp_GameResponseHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fagp_GameResponseHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fagp_GameRequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fagp_GameRequestHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014header.proto\022\010com.fagp\"[\n\022GameResponse" +
      "Header\022\013\n\003cmd\030\002 \001(\005\022\023\n\013status_code\030\003 \001(\005" +
      "\022\022\n\nstatus_msg\030\004 \001(\t\022\017\n\007version\030\005 \001(\005\"1\n" +
      "\021GameRequestHeader\022\013\n\003cmd\030\002 \001(\005\022\017\n\007versi" +
      "on\030\003 \001(\005B/\n%com.fagp.basics.core.protobu" +
      "f.aheaderB\006Headerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_fagp_GameResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fagp_GameResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fagp_GameResponseHeader_descriptor,
        new java.lang.String[] { "Cmd", "StatusCode", "StatusMsg", "Version", });
    internal_static_com_fagp_GameRequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fagp_GameRequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fagp_GameRequestHeader_descriptor,
        new java.lang.String[] { "Cmd", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
