// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lobbyResponse.proto

package com.fagp.basics.core.protobuf.lobby.response;

public final class LobbyProtoResponse {
  private LobbyProtoResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lobby.LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getHeader();
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>string phone = 2;</code>
     */
    String getPhone();
    /**
     * <code>string phone = 2;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    /**
     * <code>string vip = 3;</code>
     */
    String getVip();
    /**
     * <code>string vip = 3;</code>
     */
    com.google.protobuf.ByteString
        getVipBytes();
  }
  /**
   * <pre>
   *登录Response
   * </pre>
   *
   * Protobuf type {@code com.lobby.LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lobby.LoginResponse)
      LoginResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
      phone_ = "";
      vip_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              vip_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LobbyProtoResponse.internal_static_com_lobby_LoginResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LobbyProtoResponse.internal_static_com_lobby_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoginResponse.class, Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader header_;
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getHeader() {
      return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int PHONE_FIELD_NUMBER = 2;
    private volatile Object phone_;
    /**
     * <code>string phone = 2;</code>
     */
    public String getPhone() {
      Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIP_FIELD_NUMBER = 3;
    private volatile Object vip_;
    /**
     * <code>string vip = 3;</code>
     */
    public String getVip() {
      Object ref = vip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        vip_ = s;
        return s;
      }
    }
    /**
     * <code>string vip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVipBytes() {
      Object ref = vip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        vip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phone_);
      }
      if (!getVipBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, vip_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phone_);
      }
      if (!getVipBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, vip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoginResponse)) {
        return super.equals(obj);
      }
      LoginResponse other = (LoginResponse) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (!getVip()
          .equals(other.getVip())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (37 * hash) + VIP_FIELD_NUMBER;
      hash = (53 * hash) + getVip().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoginResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *登录Response
     * </pre>
     *
     * Protobuf type {@code com.lobby.LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lobby.LoginResponse)
        LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LobbyProtoResponse.internal_static_com_lobby_LoginResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LobbyProtoResponse.internal_static_com_lobby_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoginResponse.class, Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        phone_ = "";

        vip_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LobbyProtoResponse.internal_static_com_lobby_LoginResponse_descriptor;
      }

      @Override
      public LoginResponse getDefaultInstanceForType() {
        return LoginResponse.getDefaultInstance();
      }

      @Override
      public LoginResponse build() {
        LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LoginResponse buildPartial() {
        LoginResponse result = new LoginResponse(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.phone_ = phone_;
        result.vip_ = vip_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoginResponse) {
          return mergeFrom((LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoginResponse other) {
        if (other == LoginResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        if (!other.getVip().isEmpty()) {
          vip_ = other.vip_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder setHeader(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private Object phone_ = "";
      /**
       * <code>string phone = 2;</code>
       */
      public String getPhone() {
        Object ref = phone_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string phone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 2;</code>
       */
      public Builder setPhone(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 2;</code>
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 2;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }

      private Object vip_ = "";
      /**
       * <code>string vip = 3;</code>
       */
      public String getVip() {
        Object ref = vip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          vip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string vip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVipBytes() {
        Object ref = vip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          vip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vip = 3;</code>
       */
      public Builder setVip(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vip = 3;</code>
       */
      public Builder clearVip() {
        
        vip_ = getDefaultInstance().getVip();
        onChanged();
        return this;
      }
      /**
       * <code>string vip = 3;</code>
       */
      public Builder setVipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vip_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lobby.LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:com.lobby.LoginResponse)
    private static final LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginResponse();
    }

    public static LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      @Override
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EFTResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lobby.EFTResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getHeader();
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <pre>
     * 转账金额
     * </pre>
     *
     * <code>int32 goldNum = 3;</code>
     */
    int getGoldNum();

    /**
     * <pre>
     *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
     * </pre>
     *
     * <code>int32 tow = 4;</code>
     */
    int getTow();
  }
  /**
   * <pre>
   *转账 Response
   * </pre>
   *
   * Protobuf type {@code com.lobby.EFTResponse}
   */
  public  static final class EFTResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lobby.EFTResponse)
      EFTResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EFTResponse.newBuilder() to construct.
    private EFTResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EFTResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new EFTResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EFTResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              goldNum_ = input.readInt32();
              break;
            }
            case 32: {

              tow_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LobbyProtoResponse.internal_static_com_lobby_EFTResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LobbyProtoResponse.internal_static_com_lobby_EFTResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EFTResponse.class, Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader header_;
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getHeader() {
      return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.com.fagp.GameResponseHeader header = 1;</code>
     */
    public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int GOLDNUM_FIELD_NUMBER = 3;
    private int goldNum_;
    /**
     * <pre>
     * 转账金额
     * </pre>
     *
     * <code>int32 goldNum = 3;</code>
     */
    public int getGoldNum() {
      return goldNum_;
    }

    public static final int TOW_FIELD_NUMBER = 4;
    private int tow_;
    /**
     * <pre>
     *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
     * </pre>
     *
     * <code>int32 tow = 4;</code>
     */
    public int getTow() {
      return tow_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (goldNum_ != 0) {
        output.writeInt32(3, goldNum_);
      }
      if (tow_ != 0) {
        output.writeInt32(4, tow_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (goldNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, goldNum_);
      }
      if (tow_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tow_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EFTResponse)) {
        return super.equals(obj);
      }
      EFTResponse other = (EFTResponse) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (getGoldNum()
          != other.getGoldNum()) return false;
      if (getTow()
          != other.getTow()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + GOLDNUM_FIELD_NUMBER;
      hash = (53 * hash) + getGoldNum();
      hash = (37 * hash) + TOW_FIELD_NUMBER;
      hash = (53 * hash) + getTow();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EFTResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EFTResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EFTResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EFTResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EFTResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EFTResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EFTResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EFTResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EFTResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EFTResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EFTResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EFTResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EFTResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *转账 Response
     * </pre>
     *
     * Protobuf type {@code com.lobby.EFTResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lobby.EFTResponse)
        EFTResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LobbyProtoResponse.internal_static_com_lobby_EFTResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LobbyProtoResponse.internal_static_com_lobby_EFTResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EFTResponse.class, Builder.class);
      }

      // Construct using com.fagp.basics.core.protobuf.lobby.response.LobbyProtoResponse.EFTResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        goldNum_ = 0;

        tow_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LobbyProtoResponse.internal_static_com_lobby_EFTResponse_descriptor;
      }

      @Override
      public EFTResponse getDefaultInstanceForType() {
        return EFTResponse.getDefaultInstance();
      }

      @Override
      public EFTResponse build() {
        EFTResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EFTResponse buildPartial() {
        EFTResponse result = new EFTResponse(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.goldNum_ = goldNum_;
        result.tow_ = tow_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EFTResponse) {
          return mergeFrom((EFTResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EFTResponse other) {
        if (other == EFTResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getGoldNum() != 0) {
          setGoldNum(other.getGoldNum());
        }
        if (other.getTow() != 0) {
          setTow(other.getTow());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EFTResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EFTResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder setHeader(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      public com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.com.fagp.GameResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeader.Builder, com.fagp.basics.core.protobuf.aheader.Header.GameResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private int goldNum_ ;
      /**
       * <pre>
       * 转账金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public int getGoldNum() {
        return goldNum_;
      }
      /**
       * <pre>
       * 转账金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public Builder setGoldNum(int value) {
        
        goldNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 转账金额
       * </pre>
       *
       * <code>int32 goldNum = 3;</code>
       */
      public Builder clearGoldNum() {
        
        goldNum_ = 0;
        onChanged();
        return this;
      }

      private int tow_ ;
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public int getTow() {
        return tow_;
      }
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public Builder setTow(int value) {
        
        tow_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0 表示 从奖池转到 钱包； 1，表示 从钱包转到 奖池
       * </pre>
       *
       * <code>int32 tow = 4;</code>
       */
      public Builder clearTow() {
        
        tow_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lobby.EFTResponse)
    }

    // @@protoc_insertion_point(class_scope:com.lobby.EFTResponse)
    private static final EFTResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EFTResponse();
    }

    public static EFTResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EFTResponse>
        PARSER = new com.google.protobuf.AbstractParser<EFTResponse>() {
      @Override
      public EFTResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EFTResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EFTResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EFTResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public EFTResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_LoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_LoginResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_EFTResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_EFTResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023lobbyResponse.proto\022\tcom.lobby\032\014header" +
      ".proto\"Y\n\rLoginResponse\022,\n\006header\030\001 \001(\0132" +
      "\034.com.fagp.GameResponseHeader\022\r\n\005phone\030\002" +
      " \001(\t\022\013\n\003vip\030\003 \001(\t\"Y\n\013EFTResponse\022,\n\006head" +
      "er\030\001 \001(\0132\034.com.fagp.GameResponseHeader\022\017" +
      "\n\007goldNum\030\003 \001(\005\022\013\n\003tow\030\004 \001(\005BB\n,com.fagp" +
      ".basics.core.protobuf.lobby.responseB\022Lo" +
      "bbyProtoResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.fagp.basics.core.protobuf.aheader.Header.getDescriptor(),
        });
    internal_static_com_lobby_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lobby_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_LoginResponse_descriptor,
        new String[] { "Header", "Phone", "Vip", });
    internal_static_com_lobby_EFTResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lobby_EFTResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_EFTResponse_descriptor,
        new String[] { "Header", "GoldNum", "Tow", });
    com.fagp.basics.core.protobuf.aheader.Header.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
