// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lobby.proto

package com.fagp.basics.core.protoc.protomsg;

public final class LobbyProto {
  private LobbyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lobby_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lobby_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013lobby.proto\022\tcom.lobby\032\014header.proto\"]" +
      "\n\014LoginRequest\022,\n\006header\030\001 \001(\0132\034.com.slo" +
      "ts.GameRequestHeader\022\r\n\005phone\030\002 \001(\t\022\020\n\010p" +
      "assword\030\003 \001(\t\"m\n\rLoginResponse\022-\n\006header" +
      "\030\001 \001(\0132\035.com.slots.GameResponseHeader\022\r\n" +
      "\005phone\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\014\n\004coin\030\004" +
      " \001(\005B5\n%com.slots.basics.core.protoc.pro" +
      "tomsgB\nLobbyProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Header.getDescriptor(),
        });
    internal_static_com_lobby_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lobby_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_LoginRequest_descriptor,
        new String[] { "Header", "Phone", "Password", });
    internal_static_com_lobby_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lobby_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lobby_LoginResponse_descriptor,
        new String[] { "Header", "Phone", "Password", "Coin", });
    Header.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
