// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lobby.proto

package com.fagp.basics.core.protoc.protomsg;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lobby.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.slots.GameResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.com.slots.GameResponseHeader header = 1;</code>
   */
  Header.GameResponseHeader getHeader();
  /**
   * <code>.com.slots.GameResponseHeader header = 1;</code>
   */
  Header.GameResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>string phone = 2;</code>
   */
  String getPhone();
  /**
   * <code>string phone = 2;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string password = 3;</code>
   */
  String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int32 coin = 4;</code>
   */
  int getCoin();
}
